In [ ]:
preds

In [17]:
import numpy as np
import xgboost as xgb
import pandas as pd
import math

from sklearn.cross_validation import train_test_split
from ml_metrics import rmsle

print ('')
print ('Loading Data...')

def evalerror(preds, dtrain):

    labels = dtrain.get_label()
    assert len(preds) == len(labels)
    labels = labels.tolist()
    preds = preds.tolist()
    terms_to_sum = [(math.log(labels[i] + 1) - math.log(max(0,preds[i]) + 1)) ** 2.0 for i,pred in enumerate(labels)]
    return 'error', (sum(terms_to_sum) * (1.0/len(preds))) ** 0.5

train = pd.read_csv('../kaggle/train_downsample_50000.csv')
test = pd.read_csv('../kaggle/test.csv')

print ('')
print ('Training_Shape:', train.shape)

ids = test['id']
test = test.drop(['id'],axis = 1)

y = train['Demanda_uni_equil']
X = train[test.columns.values]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1729)

print ('Division_Set_Shapes:', X.shape, y.shape)
print ('Validation_Set_Shapes:', X_train.shape, X_test.shape)

params = {}
params['objective'] = "reg:linear"
params['eta'] = 0.1
params['max_depth'] = 10
params['subsample'] = 0.85
params['colsample_bytree'] = 0.7
params['silent'] = True

print ('')

test_preds = np.zeros(test.shape[0])
xg_train = xgb.DMatrix(X_train, label=y_train)
xg_test = xgb.DMatrix(X_test)

watchlist = [(xg_train, 'train')]
num_rounds = 100

xgclassifier = xgb.train(params, xg_train, num_rounds, watchlist, feval = evalerror, early_stopping_rounds= 20, verbose_eval = 10)
preds = xgclassifier.predict(xg_test, ntree_limit=xgclassifier.best_iteration)
print ('RMSLE Score:', rmsle(y_test.values, np.array(preds)))


#submission
#fxg_test = xgb.DMatrix(test)
#fold_preds = np.around(xgclassifier.predict(fxg_test, ntree_limit=xgclassifier.best_iteration), decimals = 1)
#test_preds += fold_preds
#
#submission = pd.DataFrame({'id':ids, 'Demanda_uni_equil': test_preds})
#submission.to_csv('submission.csv', index=False)


Loading Data...

Training_Shape: (49999, 11)
Division_Set_Shapes: (49999, 6) (49999,)
Validation_Set_Shapes: (39999, 6) (10000, 6)

[0]	train-error:1.13989
Will train until train-error hasn't improved in 20 rounds.
[10]	train-error:0.632552
[20]	train-error:0.644836
[30]	train-error:0.630746
[40]	train-error:0.623891
[50]	train-error:0.615968
[60]	train-error:0.607958
[70]	train-error:0.600154
[80]	train-error:0.592532
[90]	train-error:0.582745
[  9.3099575    4.44633532   2.98121381 ...,   7.37380362   7.731143
  18.35064316]
40862     5
9693      6
36424     6
28938     5
45424     8
35252     5
36692    10
42379     2
41357     1
27056    17
14894     2
31192    30
6246     30
24980    15
10191     1
717       1
32413     6
30541    24
6186      2
12984     2
1781      5
15995     3
27805     4
15953     4
47592    30
399       2
1855      1
39734     2
18288    19
11778     1
         ..
28535     6
38678    39
35504     3
4334      2
45143     3
3860      4
25355    10
35666    1

In [18]:
y_test.values

array([ 5,  6,  6, ..., 11, 20,  5])

In [19]:
preds

array([  9.3099575 ,   4.44633532,   2.98121381, ...,   7.37380362,
         7.731143  ,  18.35064316], dtype=float32)

In [20]:
y_test.values.shape

(10000,)

In [21]:
preds.shape

(10000,)

In [22]:
rmsle(y_test.values, np.array(preds))

nan

In [23]:
rmsle(list(y_test.values), list(np.array(preds))

SyntaxError: unexpected EOF while parsing (<ipython-input-23-64cef09b926a>, line 1)

In [24]:
rmsle(y_test.values, np.array(preds))

nan

In [25]:
y_test.values - np.array(preds)

array([ -4.3099575 ,   1.55366468,   3.01878619, ...,   3.62619638,
        12.268857  , -13.35064316])

In [26]:
(y_test.values + 1)

array([ 6,  7,  7, ..., 12, 21,  6])

In [27]:
np.log(y_test.values + 1) - np.log(np.array(preds) + 1)

array([-0.54135062,  0.2509672 ,  0.56432336, ...,  0.35979841,
        0.87762609, -1.17096617])

In [28]:
sum(np.log(y_test.values + 1) - np.log(np.array(preds) + 1))

nan

In [29]:
np.sum(np.log(y_test.values + 1) - np.log(np.array(preds) + 1))

nan

In [30]:
np.sum(np.log(y_test.values + 1) - np.log(np.array(preds) + 1), axis=0)

nan

In [31]:
np.sum(np.log(y_test.values + 1) - np.log(np.array(preds) + 1), axis=1)

ValueError: 'axis' entry is out of bounds

In [32]:
np.log(y_test.values + 1) - np.log(np.array(preds) + 1)

array([-0.54135062,  0.2509672 ,  0.56432336, ...,  0.35979841,
        0.87762609, -1.17096617])

In [33]:
sum(np.log(y_test.values + 1) - np.log(np.array(preds) + 1))

nan

In [34]:
np.sum(np.log(y_test.values + 1) - np.log(np.array(preds) + 1))

nan